# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('avg_rating', models.FloatField()),
                ('product_grade', models.FloatField()),
                ('decoration_grade', models.FloatField()),
                ('service_grade', models.FloatField()),
                ('avg_price', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('hours', models.CharField(max_length=100)),
                ('has_takeaway', models.BooleanField()),
                ('has_online_reservation', models.BooleanField()),
                ('recommend_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('radius', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('catagory', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=50)),
                ('sort', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dianping.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('excertpt', models.CharField(max_length=50)),
                ('grade', models.FloatField()),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dianping.Business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('browsed_list', models.ManyToManyField(to='dianping.Business')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='dianping.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='dianping.User'),
        ),
    ]
