# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0002_auto_20170701_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='avg_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='avg_rating',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='branch_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='decoration_grade',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='has_online_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='has_takeaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='hours',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='product_grade',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='recommend_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='region',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='service_grade',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
