# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0003_auto_20170701_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
