# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0004_business_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='hours',
        ),
        migrations.AddField(
            model_name='business',
            name='shop_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='business',
            name='star',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='decoration_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='has_online_reservation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='has_takeaway',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='product_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='service_grade',
            field=models.FloatField(default=0),
        ),
    ]
