# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0008_auto_20170705_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='excerpt',
            field=models.TextField(default=''),
        ),
    ]
