# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0009_auto_20170705_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='popular_dishes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
