# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0011_auto_20170706_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_review', to='dianping.Business'),
        ),
    ]
