# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0013_auto_20170707_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianpinguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dianpinguser', to=settings.AUTH_USER_MODEL),
        ),
    ]
