# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0014_auto_20170707_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dianpinguser',
            name='starred_list',
        ),
        migrations.RemoveField(
            model_name='dianpinguser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='DianpingUser',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
