# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0016_auto_20170707_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
