# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0021_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
