# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0023_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
    ]
