# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0024_remove_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
