# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0029_auto_20170708_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file_num',
            field=models.IntegerField(default=-1),
        ),
    ]
