# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dianping', '0030_review_file_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
